### ISSUE TITLE
Address.District

### ISSUE THREAD

**Issue by ViniciusTardem** [hugobritobh/Cielo3.0#1]
Olá Hugo, tudo bem ?

Estive configurando em um cliente a api 3.0 para asp.net 4.5

E estou tendo uma situação com a class Address.

Dentro do código que eu puxei e também na consulta aqui no Git, me parece estar faltando um campo ou não consegui chamar esse campo que é obrigatório: Address.District.

Aparentemente é obrigatório mas não possui dentro do código, como posso proceder?

Obrigado desde já!

**Comment by hugobritobh** [comment]
Bom dia!
Vou analisar e aproveitar para atualizar os packages.

**Comment by ViniciusTardem** [comment]
Maravilha Hugo! Eu agradeço!

Se precisar de algo, estou a disposição!

**Comment by hugobritobh** [comment]
Realmente não tinha. Adicionei, verifiquei que tem uma regra nos campos de endereço e criei três novos casos de testes (um dele para regra do endereço).

Aproveitei para atualizar o framework .NET e os packages ... 
Demora alguns minutos para aparecer no Nuget

**Comment by hugobritobh** [comment]
Versão 1.0.15

Adicionado o NetStandard 2.1, .NET 4.8 e 4.7.1

Adicionado o campo District

Troca de Microsoft.Net.Http 2.2.29 para System.Net.Http 4.3.4

Acertei a dependência do System.Net.Http no package ....
