### ISSUE TITLE
Recorrência sem data fim

### ISSUE THREAD

**Issue by brzuck** [hugobritobh/Cielo3.0#2]
Olá,

Pela documentação da Cielo seria possível criar uma transação recorrente sem informar uma data fim.

Seria possível alterar o contrutor de RecurrentPayment para permitir isso?

Será que só assim eu consigo o mesmo efeito?
```
            var recurrent = new RecurrentPayment();
            recurrent.SetInterval(meuintervalo);
```

Obrigado

**Comment by hugobritobh** [comment]
Eu não lembro quando criei era necessário. 
Para resolver isso colocamos a recorrência pra terminar daqui 20 anos (algo assim não lembro direito). 
É bom ressaltar que uma recorrência pode ser cancelada "manualmente" pela API (caso o usuário queira).

Estou meio apertado, mas creio que até Domingo já tenha criado os casos de teste para verificar essa situação.
Caso funcione eu altero sem problema;

**Comment by brzuck** [comment]
Perfeito!
No único exemplo que eles dão, eles informam a data fim. Mas na tabelinha que descreve as propriedades, o campo é citado como opcional.
Eles até citam um caso de uso da empresa _Musicfy_ que tem esse esquema de assinatura sem data fim.
