### ISSUE TITLE
Internal Server Error - Pagamento com recorrência

### ISSUE THREAD

**Issue by brzuck** [hugobritobh/Cielo3.0#3]
Estou tendo um erro ao tentar criar um pagamento usando recorrência.

Usando o GetCieloErrors():
```
[
   {
      "Code":0,
      "Message":"Error code InternalServerError."
   }
]
```

Estou montando a transação dessa maneira:
```
            var customer = new Customer(user.FullName);
            var card = new Card(input.CartaoNumero, input.CartaoNomeImpresso, input.CartaoExpiracao, input.CartaoCodigo, input.CartaoBandeira);
            var recurrent = new RecurrentPayment(plano.Intervalo, DateTime.Today.AddYears(5));
            var payment = new Payment(plano.Valor, Currency.BRL, 1, true, null, card, recurrentPayment: recurrent);
            var transaction = new Transaction(orderId, customer, payment);
```

E o objeto gerado que é enviado no CreateTransactionAsync() fica assim:
```
{
   "MerchantOrderId":"e4e5be04-db53-454c-b39b-c9e3faeb97ec",
   "Customer":{
      "Name":"admin admin",
      "Identity":null,
      "IdentityType":null,
      "Email":null,
      "Birthdate":null,
      "Address":null,
      "DeliveryAddress":null
   },
   "Payment":{
      "Installments":1,
      "Interest":null,
      "Capture":true,
      "Authenticate":null,
      "Recurrent":null,
      "RecurrentPayment":{
         "RecurrentPaymentId":null,
         "AuthorizeNow":true,
         "StartDate":null,
         "EndDate":"2025-07-09",
         "NextRecurrency":null,
         "Interval":"Monthly",
         "Links":null,
         "ReasonCode":null,
         "ReasonMessage":null,
         "SuccessfulRecurrences":0,
         "RecurrentTransactions":null,
         "Status":null
      },
      "CreditCard":{
         "CardNumber":"0000000000000001",
         "CardToken":null,
         "Holder":"TESTE",
         "CustomerName":null,
         "ExpirationDate":"08/2020",
         "SecurityCode":"123",
         "SaveCard":false,
         "Brand":"Visa"
      },
      "Tid":null,
      "ProofOfSale":null,
      "AuthorizationCode":null,
      "AuthenticationUrl":null,
      "BoletoNumber":null,
      "Instructions":null,
      "Country":"BRA",
      "ExtraDataCollection":null,
      "ExpirationDate":null,
      "Url":null,
      "Number":null,
      "BarCodeNumber":null,
      "DigitableLine":null,
      "Address":null,
      "SoftDescriptor":null,
      "ReturnUrl":"",
      "Wallet":null,
      "Provider":null,
      "PaymentId":null,
      "Type":"CreditCard",
      "ServiceTaxAmount":null,
      "Amount":"544",
      "CapturedAmount":null,
      "ReceivedDate":null,
      "CapturedDate":null,
      "FraudAnalysis":null,
      "Currency":"BRL",
      "DebitCard":null,
      "CardToken":null,
      "ReturnCode":null,
      "ReturnMessage":null,
      "ReasonCode":null,
      "ReasonMessage":null,
      "ProviderReturnCode":null,
      "ProviderReturnMessage":null,
      "Status":null,
      "Links":null
   }
}
```

**Comment by hugobritobh** [comment]
Eu usei o teste unitário para ver e continua funcionando.
Você consegue fazer uma transação normal (sem ser recorrente) ?

![image](https://user-images.githubusercontent.com/8490666/87064226-ca10ed80-c1e5-11ea-98f5-dbc441183d27.png)

Json gerado:

{
  "MerchantOrderId": "976704542",
  "Customer": {
    "Name": "Hugo Alves",
    "Identity": null,
    "IdentityType": null,
    "Email": null,
    "Birthdate": null,
    "Address": null,
    "DeliveryAddress": null
  },
  "Payment": {
    "Installments": 1,
    "Interest": null,
    "Capture": null,
    "Authenticate": null,
    "Recurrent": null,
    "RecurrentPayment": {
      "RecurrentPaymentId": null,
      "AuthorizeNow": true,
      "StartDate": null,
      "EndDate": "2040-07-09",
      "NextRecurrency": null,
      "Interval": "Monthly",
      "Links": null,
      "ReasonCode": null,
      "ReasonMessage": null,
      "SuccessfulRecurrences": 0,
      "RecurrentTransactions": null,
      "Status": null
    },
    "CreditCard": {
      "CardNumber": "4674949725897271",
      "CardToken": null,
      "Holder": "Hugo de Brito V R Alves",
      "CustomerName": null,
      "ExpirationDate": "07/2022",
      "SecurityCode": "123",
      "SaveCard": false,
      "Brand": "Visa"
    },
    "Tid": null,
    "ProofOfSale": null,
    "AuthorizationCode": null,
    "AuthenticationUrl": null,
    "BoletoNumber": null,
    "Instructions": null,
    "Country": "BRA",
    "ExtraDataCollection": null,
    "ExpirationDate": null,
    "Url": null,
    "Number": null,
    "BarCodeNumber": null,
    "DigitableLine": null,
    "Address": null,
    "SoftDescriptor": null,
    "ReturnUrl": null,
    "Wallet": null,
    "Provider": null,
    "PaymentId": null,
    "Type": "CreditCard",
    "ServiceTaxAmount": null,
    "Amount": "15002",
    "CapturedAmount": null,
    "ReceivedDate": null,
    "CapturedDate": null,
    "FraudAnalysis": null,
    "Currency": "BRL",
    "DebitCard": null,
    "CardToken": null,
    "ReturnCode": null,
    "ReturnMessage": null,
    "ReasonCode": null,
    "ReasonMessage": null,
    "ProviderReturnCode": null,
    "ProviderReturnMessage": null,
    "Status": null,
    "Links": null
  }
}

**Comment by brzuck** [comment]
Sem ser recorrente funcionou sem problemas.

Aparentemente, a única diferença entre o meu e o seu parece ser a propriedade Capture de Payment. No seu está nulo e no meu ficou setado como true

**Comment by hugobritobh** [comment]
Tenta utilizar os dados do cartão (q utilizei) e Capture (null) e vê se funciona...

Lembrando que isso encontra-se no projeto de teste caso queira pegar como exemplo.

**Comment by brzuck** [comment]
Hehe pode ignorar. O problema era no número de cartão, mas de qualquer forma poderia retornar um erro tratado de número inválido.
Consegui usar mesmo com o capture true.

Obrigado pela atenção
